wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.0
    framework: huggingface
    huggingface_version: 4.42.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721355306
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 98
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 63
      - 71
      - 98
      - 105
      3:
      - 23
      4: 3.8.19
      5: 0.17.0
      6: 4.42.3
      8:
      - 5
      13: linux-x86_64
